// Contrato JSON injetado server-side quando o cliente do verbo é
// (a) autenticado e (b) o verbo está em STRUCTURED_MODES. Mantém o
// jo-<verbo>.md focado em diagnóstico/conteúdo, sem condicionais "se
// logado/anônimo" — o LLM não conhece o estado de sessão.
//
// Camada 3 (Carla, 2026-05-12):
//  - Hooks hardcoded a partir de ALL_HOOK_IDS (fonte: hooks.ts) pra
//    eliminar alucinação de chaves inexistentes.
//  - Trava lógica: NO_GO ⇒ route_order = [].
//  - `markdown` POR ÚLTIMO (ordem importa pro streaming-parser extrair
//    cabeçalho cedo).

import { ALL_HOOK_IDS } from '../../diagnostico/hooks';
import type { JoMode } from './index';

const VALID_VERBS = ['estruturar', 'formalizar', 'construir', 'avaliar', 'manter'];

// Contrato pra Mapear — Relatório de Diagnóstico Institucional (Passo 0).
// ARQUITETURA SECTIONS-FIRST: emite só metadata + sections list. Cada section
// é gerada em call separada (/api/journey/section) com hard caps anti-prolixidade.
// Mantém hookIds canônicos no diagnostic_tags (24 chaves fechadas, anti-alucinação).
function mapearContract(hookIds: readonly string[]): string {
  const hookList = hookIds.map((id) => `   - "${id}"`).join('\n');
  const verbList = VALID_VERBS.map((v) => `"${v}"`).join(', ');

  return [
    '---',
    '',
    '# CONTRATO DE SAÍDA — JSON ESTRITO',
    '',
    'Sua resposta DEVE ser exclusivamente um objeto JSON válido. Sem texto antes',
    'ou depois. Sem blocos de código \\`\\`\\`json\\`\\`\\`. O sistema parseia e',
    'renderiza a saída — qualquer ruído quebra a UI.',
    '',
    'Dois formatos possíveis — escolha um conforme o input do servidor.',
    '',
    '## Formato 1 — Devolução técnica (input insuficiente)',
    '',
    'Use quando o cenário descrito carecer de matéria-prima institucional:',
    'cenário vago (sem ator/tema/órgão), atores não nominados, gargalo genérico',
    'sem ponto de atrito específico, risco não quantificado.',
    '',
    '{',
    '  "type": "devolucao",',
    '  "checklist": [',
    '    { "ok": false, "label": "Cenário concreto",            "hint": "Especifique órgão + tema + estágio do lab + janela política" },',
    '    { "ok": false, "label": "Atores nominados",            "hint": "Cite nome+cargo do patrocinador e equipe-chave" },',
    '    { "ok": false, "label": "Gargalo técnico identificado", "hint": "Aponte o ponto específico de atrito (jurídico/metodológico/operacional/político)" },',
    '    { "ok": false, "label": "Risco quantificado",           "hint": "Indique cenário negativo plausível e prazo (ex: descontinuidade na transição de 06/2026)" }',
    '  ],',
    '  "next": "Refine os campos marcados e regere — o wizard segue aberto.",',
    '  "message": "Frase curta de contexto antes do checklist (opcional)."',
    '}',
    '',
    'IMPORTANTE: o checklist DEVE ter EXATAMENTE 4 itens nesta ordem (Cenário,',
    'Atores, Gargalo, Risco) — o frontend alinha edição inline aos 4 textareas.',
    '',
    'ACEITAÇÃO FLEXÍVEL — princípio operacional:',
    'O wizard fornece chips com elementos-chave por campo. Aceite tanto frases',
    'completas quanto listas de elementos separados por " · " desde que os',
    'elementos centrais estejam presentes. NÃO use devolucao só por ausência de',
    'hookId aplicável (devolva plan com diagnostic_tags: []).',
    '',
    '## Formato 2 — Plan (Relatório de Diagnóstico planejado em seções)',
    '',
    'NÃO escreva o conteúdo do Relatório aqui. Só o esqueleto. O sistema vai',
    'pedir cada seção em call separada, sob constraints específicos.',
    '',
    '{',
    '  "type": "plan",',
    '  "title": "Relatório de Diagnóstico — <recorte curto, ex: \'Lab estadual de saúde sem portaria, janela 90d\'>",',
    '  "summary": "Resumo de até 200 caracteres com lab + gargalo central + risco principal",',
    '  "goNoGo": "GO" | "GO_MITIGATION" | "NO_GO",',
    '  "route_order": [...],',
    '  "diagnostic_tags": [...],',
    '  "sections": [',
    '    { "id": "identificacao",         "title": "Identificação Institucional" },',
    '    { "id": "considerandos",         "title": "Considerandos" },',
    '    { "id": "analise-risco-familias", "title": "Análise de Risco por Família" },',
    '    { "id": "matriz-e-decisao",      "title": "Matriz de Riscos e Diretriz Go/No-Go" },',
    '    { "id": "caveat-fundamentacao",  "title": "Da Fundamentação e Caveat" }',
    '  ]',
    '}',
    '',
    '### Regras estritas',
    '',
    '**1. type** — literalmente `"plan"`.',
    '',
    '**2. title** — frase curta (≤80 chars) com recorte do diagnóstico.',
    '',
    '**3. goNoGo** — literais exatos (case-sensitive):',
    '   - "GO": cenário viável, segue pra próximos verbos.',
    '   - "GO_MITIGATION": viável com ressalvas (detalhadas nas sections).',
    '   - "NO_GO": cenário inviável (judicial, ministerial trancado, jurisdição',
    '     alheia) — o processo morre aqui. Roteie no campo `markdown` da seção',
    '     `caveat-fundamentacao` pra foro adequado.',
    '',
    `**4. route_order** — array com 0 a 5 verbos da sequência recomendada.`,
    `   Verbos válidos: ${verbList}.`,
    '   **TRAVA LÓGICA OBRIGATÓRIA**: se goNoGo = "NO_GO", route_order DEVE',
    '   ser exatamente [] (array vazio).',
    '',
    '**5. diagnostic_tags** — array de 0 a 5 chaves. ESCOLHA EXCLUSIVAMENTE',
    '   desta lista fechada (24 hookIds canônicos · cópia caractere-a-caractere):',
    '',
    hookList,
    '',
    '   É PROIBIDO inventar chaves novas, variantes, traduções ou abreviações.',
    '   Quando nenhum hook se aplicar honestamente, devolva `diagnostic_tags: []`.',
    '',
    '**6. summary** — string de até 200 caracteres. Alimenta [CONTEXTO_PRÉVIO]',
    '   dos próximos verbos — seja denso e específico, sem adjetivos vazios.',
    '',
    '**7. sections** — array com EXATAMENTE estas 5 seções nesta ordem e com',
    '   estes id+title literais. NÃO crie seções extras, NÃO renomeie, NÃO',
    '   reordene. O sistema gera o conteúdo de cada uma sob comando separado.',
    '',
    '**NÃO INCLUA** campo `markdown` no plan — esse é do shape relatorio antigo.',
    '',
  ].join('\n');
}

// Contrato pra Estruturar — output é um Blueprint de Sprint (MINDS + InovaGov).
// ARQUITETURA SECTIONS-FIRST (2026-05-12): o LLM emite só metadata + sections
// list (sem markdown). Cada seção é gerada em call separada (/api/journey/section)
// com prompt focado e budget pequeno — timeout afeta UMA seção, não o doc inteiro.
//
// Sobre o JSON aqui: pequeno, determinístico, raramente trunca. ~500 bytes.
function estruturarContract(): string {
  const verbList = VALID_VERBS.map((v) => `"${v}"`).join(', ');
  return [
    '---',
    '',
    '# CONTRATO DE SAÍDA — JSON ESTRITO',
    '',
    'Sua resposta DEVE ser exclusivamente um objeto JSON válido. Sem texto antes',
    'ou depois. Sem blocos de código \\`\\`\\`json\\`\\`\\`. O sistema parseia e',
    'renderiza a saída — qualquer ruído quebra a UI.',
    '',
    'Dois formatos possíveis — escolha um conforme o input do servidor.',
    '',
    '## Formato 1 — Devolução técnica (input insuficiente)',
    '',
    'Use quando o input carecer de matéria-prima pra desenhar Sprint: problema',
    'genérico (sem serviço/órgão/impacto observável), hipótese travestida de',
    'solução (afirma a resposta antes do teste), experimento sem amostra,',
    'duração ou sinal de sucesso mensurável.',
    '',
    '{',
    '  "type": "devolucao",',
    '  "checklist": [',
    '    { "ok": false, "label": "Problema concreto",     "hint": "Especifique serviço + órgão + impacto observável (ex: evasão de 40% em perícias)" },',
    '    { "ok": false, "label": "Hipótese testável",     "hint": "Indique causa-raiz E mecanismo de mudança. Pode ser frase Se/Então/Porque OU lista de elementos-chave (ex: \'Canal inadequado · Aumenta visibilidade\')." },',
    '    { "ok": false, "label": "Experimento mensurável", "hint": "Defina amostra, duração e sinal de sucesso. Pode ser frase OU lista de elementos (ex: \'30 dias · Tempo de resolução · A/B controle\')." }',
    '  ],',
    '  "next": "Refine os campos marcados e regere — o wizard segue aberto.",',
    '  "message": "Frase curta de contexto antes do checklist (opcional)."',
    '}',
    '',
    'IMPORTANTE: o checklist DEVE ter EXATAMENTE 3 itens nesta ordem (Problema,',
    'Hipótese, Experimento) — o frontend alinha edição inline aos 3 textareas.',
    '',
    'ACEITAÇÃO FLEXÍVEL — princípio operacional:',
    'O wizard fornece chips com elementos-chave por campo (causa-raiz, mecanismo,',
    'amostra, duração, intervenção, sinal de sucesso, etc.). Aceite tanto frases',
    'completas quanto listas de elementos separados por " · " (formato dos chips)',
    'desde que os elementos CENTRAIS estejam presentes:',
    '  - Hipótese: causa-raiz + mecanismo (mínimo). NÃO exija Se/Então/Porque literal.',
    '  - Experimento: amostra + duração + sinal de sucesso (mínimo).',
    'Quando os elementos estão presentes em qualquer formato, considere ✓ e prossiga',
    'pra plan. Você compõe a sintaxe formal internamente no markdown das seções.',
    '',
    '## Formato 2 — Plan (Blueprint planejado em seções)',
    '',
    'NÃO escreva o conteúdo do Blueprint aqui. Só o esqueleto. O sistema vai',
    'pedir cada seção em call separada, sob constraints específicos.',
    '',
    '{',
    '  "type": "plan",',
    '  "title": "Blueprint do Sprint — <recorte curto do problema, ex: \'Evasão em perícias médicas\'>",',
    '  "summary": "Resumo de até 200 caracteres mencionando hipótese central + sinal de sucesso",',
    '  "route_order": [...],',
    '  "sections": [',
    '    { "id": "fase-1-entender",  "title": "Fase 1 — Entender" },',
    '    { "id": "fase-2-explorar",  "title": "Fase 2 — Explorar" },',
    '    { "id": "fase-3-entregar",  "title": "Fase 3 — Entregar" },',
    '    { "id": "papeis-ritos",     "title": "Papéis e Ritos" },',
    '    { "id": "cronograma",       "title": "Cronograma" },',
    '    { "id": "indicadores",      "title": "Indicadores" },',
    '    { "id": "caveat",           "title": "Caveat Jurídico" }',
    '  ]',
    '}',
    '',
    '### Regras estritas',
    '',
    '**1. type** — literalmente `"plan"`.',
    '',
    '**2. title** — frase curta (≤80 chars) com recorte do problema.',
    '',
    `**3. route_order** — array com 1 a 4 verbos. Verbos válidos: ${verbList}.`,
    '   Sugira sequência natural pós-Sprint. Default: `["construir", "avaliar"]`.',
    '   Quando há trava jurídica antes do piloto: `["formalizar", "construir"]`.',
    '',
    '**4. summary** — string de até 200 caracteres. Alimenta [CONTEXTO_PRÉVIO]',
    '   dos próximos verbos. Densidade > prosa.',
    '',
    '**5. sections** — array com EXATAMENTE estas 7 seções nesta ordem e com',
    '   estes id+title literais. NÃO crie seções extras, NÃO renomeie, NÃO',
    '   reordene. O sistema gera o conteúdo de cada uma sob comando separado.',
    '',
    '**NÃO INCLUA** campo `markdown`, `goNoGo` ou `diagnostic_tags`. Esses são',
    'do shape antigo (relatorio) que não usamos mais aqui.',
    '',
  ].join('\n');
}

// Contrato pra Avaliar — Plano de Avaliação (Theory of Change + Matriz SMART).
// Sections-first. Variável crítica: Escopo (backoffice vs serviço-fim) drives
// quais Dimensões de Valor são permitidas (anti-alucinação cidadã em backoffice).
function avaliarContract(): string {
  const verbList = VALID_VERBS.map((v) => `"${v}"`).join(', ');
  return [
    '---',
    '',
    '# CONTRATO DE SAÍDA — JSON ESTRITO',
    '',
    'Sua resposta DEVE ser exclusivamente um objeto JSON válido. Sem texto antes',
    'ou depois. Sem code fences. O sistema parseia e renderiza — qualquer ruído quebra.',
    '',
    '## Formato 1 — Devolução técnica (input insuficiente)',
    '',
    'Use quando: intervenção sem nome/escopo definido; outcome sem dimensão de valor',
    'declarada; dados sem fonte ou periodicidade. NÃO tente adivinhar.',
    '',
    '{',
    '  "type": "devolucao",',
    '  "checklist": [',
    '    { "ok": false, "label": "Intervenção identificada", "hint": "Nomeie a intervenção + escopo (backoffice ou serviço-fim) + duração" },',
    '    { "ok": false, "label": "Outcome com dimensão",      "hint": "Indique mudança esperada + dimensão de valor (Administrativa/Cidadã/Societal/Econômica)" },',
    '    { "ok": false, "label": "Fonte de dados nominada",   "hint": "Cite sistema/instrumento (SEI, BI, survey) + periodicidade" }',
    '  ],',
    '  "next": "Refine os campos marcados e regere — o wizard segue aberto.",',
    '  "message": "Frase curta de contexto antes do checklist (opcional)."',
    '}',
    '',
    'IMPORTANTE: o checklist DEVE ter EXATAMENTE 3 itens nesta ordem (Intervenção,',
    'Outcome, Dados) — o frontend alinha edição inline aos 3 textareas.',
    '',
    'ACEITAÇÃO FLEXÍVEL: aceite frase OU lista por " · " (formato dos chips)',
    'desde que os elementos centrais estejam presentes.',
    '',
    '## Formato 2 — Plan (Plano de Avaliação planejado em seções)',
    '',
    '{',
    '  "type": "plan",',
    '  "title": "Plano de Avaliação — <recorte curto, ex: \'Capacitação ágil em licenciamento ambiental\'>",',
    '  "summary": "Resumo de até 200 caracteres com intervenção + dimensão central + horizonte",',
    '  "route_order": [...],',
    '  "sections": [',
    '    { "id": "contextualizacao-pergunta",   "title": "Contextualização e Pergunta de Avaliação" },',
    '    { "id": "teoria-mudanca",              "title": "Teoria de Mudança" },',
    '    { "id": "criterios-dac",               "title": "Critérios DAC Aplicáveis" },',
    '    { "id": "matriz-indicadores",          "title": "Matriz de Indicadores" },',
    '    { "id": "plano-coleta-salvaguardas",   "title": "Plano de Coleta e Salvaguardas Anti-Viés" },',
    '    { "id": "caveat-fundamentacao",        "title": "Da Fundamentação e Caveat" }',
    '  ]',
    '}',
    '',
    '### Regras estritas',
    '',
    '**1. type** — literalmente `"plan"`.',
    '',
    `**2. route_order** — array com 0 a 3 verbos. Verbos válidos: ${verbList}.`,
    '   Default razoável após Avaliar: `["manter"]` (defesa retroativa via dossiê).',
    '   Se a avaliação revelar lacunas: `["estruturar"]` ou `["construir"]`.',
    '',
    '**3. summary** — string ≤ 200 chars. Densidade > prosa. Mencione intervenção +',
    '   dimensão de valor central + horizonte de medição.',
    '',
    '**4. sections** — EXATAMENTE 6 seções nesta ordem com estes id+title literais.',
    '',
    'CRÍTICO — anti-alucinação por escopo (item 4 do jo-avaliar.md):',
    '- Escopo BACKOFFICE → indicadores APENAS Administrativa + Econômica.',
    '  PROIBIDO forçar Cidadã ou Societal em projeto interno (capacitação RH,',
    '  reorganização, automação backoffice). Métrica cidadã alucinada enfraquece.',
    '- Escopo SERVIÇO-FIM → ao menos 1 indicador Cidadã ou Societal é OBRIGATÓRIO.',
    '  Sem isso, o plano roda em "modo eficiência interna" e a defesa fica fragilizada.',
    '',
    '**NÃO INCLUA** campo `markdown`, `goNoGo` ou `diagnostic_tags`.',
    '',
  ].join('\n');
}

// Contrato pra Construir — Plano de Implementação Técnica + Handoff (LABORI/AGU).
// Sections-first. CRÍTICO: sem unidade executora declarada (Step 4), Jô bloqueia.
function construirContract(): string {
  const verbList = VALID_VERBS.map((v) => `"${v}"`).join(', ');
  return [
    '---',
    '',
    '# CONTRATO DE SAÍDA — JSON ESTRITO',
    '',
    'Sua resposta DEVE ser exclusivamente um objeto JSON válido. Sem texto antes',
    'ou depois. Sem code fences.',
    '',
    '## Formato 1 — Devolução técnica (input insuficiente)',
    '',
    'Use quando: solução não validada (concept sem teste); stack sem definição mínima;',
    'restrição de TI vaga; **unidade executora ausente** (não há handoff sem destinatário).',
    '',
    '{',
    '  "type": "devolucao",',
    '  "checklist": [',
    '    { "ok": false, "label": "Solução validada",          "hint": "Indique tipo + maturidade (concept/MVP/validado) + métricas do piloto se houver" },',
    '    { "ok": false, "label": "Stack definida",            "hint": "Indique no-code/lo-code/custom + ferramenta principal + justificativa" },',
    '    { "ok": false, "label": "Restrições mapeadas",       "hint": "Cite restrições TI (fila/LGPD/legacy) + janela + camada normativa aplicável" },',
    '    { "ok": false, "label": "Unidade executora declarada", "hint": "OBRIGATÓRIO: nomeie quem assume a operação após o handoff (área/autarquia/parceiro)" }',
    '  ],',
    '  "next": "Refine os campos marcados e regere — sem unidade executora não há handoff possível.",',
    '  "message": "Frase curta de contexto antes do checklist (opcional)."',
    '}',
    '',
    'IMPORTANTE: o checklist DEVE ter EXATAMENTE 4 itens nesta ordem (Solução, Stack,',
    'Restrições, Unidade) — alinhado aos 4 textareas do wizard.',
    '',
    '## Formato 2 — Plan (Plano de Implementação planejado em seções)',
    '',
    '{',
    '  "type": "plan",',
    '  "title": "Plano de Implementação — <recorte curto, ex: \'Chatbot previdenciário · CGAC/INSS\'>",',
    '  "summary": "Resumo de até 200 caracteres com solução + stack + unidade destinatária + janela",',
    '  "route_order": [...],',
    '  "sections": [',
    '    { "id": "contextualizacao",       "title": "Contextualização e Objetivo" },',
    '    { "id": "caminho-vale-da-morte",  "title": "Caminho na Cadeia Vale da Morte" },',
    '    { "id": "plano-tecnico",          "title": "Plano de Implementação Técnica" },',
    '    { "id": "handoff-descontinuidade", "title": "Plano de Handoff e Descontinuidade" },',
    '    { "id": "tct-minuta",             "title": "Termo de Cooperação Técnica (minuta)" },',
    '    { "id": "caveat-fundamentacao",   "title": "Da Fundamentação e Caveat" }',
    '  ]',
    '}',
    '',
    '### Regras estritas',
    '',
    '**1. type** — literalmente `"plan"`.',
    '',
    `**2. route_order** — array com 0 a 3 verbos. Verbos válidos: ${verbList}.`,
    '   Default razoável após Construir: `["avaliar", "manter"]` (medir e sustentar).',
    '',
    '**3. summary** — string ≤ 200 chars. Mencione solução + stack + unidade destinatária.',
    '',
    '**4. sections** — EXATAMENTE 6 seções nesta ordem com estes id+title literais.',
    '',
    'CRÍTICO — Cadeia Vale da Morte (jo-construir.md item 1):',
    '- Avalie qual instrumento cabe: Encomenda Tec (10.973), CPSI (14.133/Lei Gov Digital), Sandbox AGU.',
    '- Não trate como peças isoladas — explicite onde o caso entra na cadeia.',
    '- Se Sandbox ou CPSI: OBRIGATÓRIO Plano de Descontinuidade Planejada + Transição p/ Regulação Plena.',
    '',
    '**NÃO INCLUA** campo `markdown`, `goNoGo` ou `diagnostic_tags`.',
    '',
  ].join('\n');
}

// Contrato pra Manter — Pacote de Continuidade Institucional (4 peças).
// Sections-first. CRÍTICOS:
//  - "Patrocinador único" no input → Jô embute ALERTA DE FRAGILIDADE.
//  - Sem indicadores de outcome → modo "defesa retroativa" declarado.
//  - "LISP" auto-corrigido pra "Mapeamento LISP Brasil".
function manterContract(): string {
  const verbList = VALID_VERBS.map((v) => `"${v}"`).join(', ');
  return [
    '---',
    '',
    '# CONTRATO DE SAÍDA — JSON ESTRITO',
    '',
    'Sua resposta DEVE ser exclusivamente um objeto JSON válido. Sem texto antes',
    'ou depois. Sem code fences.',
    '',
    '## Formato 1 — Devolução técnica (input insuficiente)',
    '',
    'Use APENAS quando: Step 1 (Entregas) não declara nenhuma peça com lastro ' +
      '(portaria/TCT/sistema/indicador). Manter COMPÕE — sem insumos, não há o ' +
      'que compor. Patrocinador único NÃO é motivo de devolução (gera alerta no plan).',
    '',
    '{',
    '  "type": "devolucao",',
    '  "checklist": [',
    '    { "ok": false, "label": "Entregas com lastro",      "hint": "Liste pelo menos 1 peça nominada (portaria DOU XX/XXXX, TCT YY/XXXX, indicador medido)" },',
    '    { "ok": false, "label": "Janela e audiência",       "hint": "Indique janela política (transição/defesa/contas) + audiência primária (alta gestão/sucessor/controle externo)" },',
    '    { "ok": false, "label": "Risco de descontinuidade", "hint": "Nomeie o patrocinador atual + sintomas de fragilidade (média gerência, redes, dedicação)" },',
    '    { "ok": false, "label": "Pedido de continuidade",   "hint": "Especifique recursos (orçamento/FCE/horas/infra) + redes-alvo (InovaGov/RenovaJud/LISP)" }',
    '  ],',
    '  "next": "Refine os campos marcados — sem entregas formalizadas, encaminhe primeiro pra Avaliar/Formalizar/Construir.",',
    '  "message": "Frase curta de contexto antes do checklist (opcional)."',
    '}',
    '',
    'IMPORTANTE: o checklist DEVE ter EXATAMENTE 4 itens nesta ordem.',
    '',
    '## Formato 2 — Plan (Pacote de Continuidade planejado em seções)',
    '',
    '{',
    '  "type": "plan",',
    '  "title": "Pacote de Continuidade — <recorte curto, ex: \'Lab SEMARH · transição 06/2026\'>",',
    '  "summary": "Resumo de até 200 caracteres mencionando lab + janela + risco principal de continuidade",',
    '  "route_order": [...],',
    '  "sections": [',
    '    { "id": "dossie-transicao",       "title": "Dossiê de Transição Institucional" },',
    '    { "id": "briefing-executivo",     "title": "Briefing Executivo de Transição" },',
    '    { "id": "plano-sustentabilidade", "title": "Plano de Sustentabilidade e Ecossistema" },',
    '    { "id": "minutas-adesao-redes",   "title": "Minutas de Adesão à Rede" },',
    '    { "id": "caveat-fundamentacao",   "title": "Da Fundamentação e Caveat" }',
    '  ]',
    '}',
    '',
    '### Regras estritas',
    '',
    '**1. type** — literalmente `"plan"`.',
    '',
    `**2. route_order** — array com 0 a 3 verbos. Verbos válidos: ${verbList}.`,
    '   Se Step 1 não declarou outcome, recomendar `["avaliar"]` (defesa retroativa).',
    '',
    '**3. summary** — string ≤ 200 chars. Mencione lab + janela política + risco principal.',
    '',
    '**4. sections** — EXATAMENTE 5 seções nesta ordem com estes id+title literais.',
    '',
    'TRIGGERS OBRIGATÓRIOS NO CONTEÚDO DAS SECTIONS:',
    '- "Patrocinador único" no Step 3 → embutir bloco "⚠ ALERTA DE FRAGILIDADE ' +
      'INSTITUCIONAL" na ABERTURA do briefing-executivo E em seção destacada do ' +
      'plano-sustentabilidade. Texto literal do alerta vem no jo-manter.md item 4.',
    '- Sem indicadores de outcome no Step 1 → declarar "modo defesa retroativa" no ' +
      'sumário do dossie-transicao e na abertura do briefing-executivo.',
    '- "LISP" como instituição filiável → auto-corrigir silenciosamente para ' +
      '"Mapeamento LISP Brasil — plataforma do Observatório de Laboratórios de ' +
      'Inovação no Setor Público da UFRN, construída a partir da metodologia de ' +
      'diagnóstico da Enap" no texto da minutas-adesao-redes.',
    '',
    '**NÃO INCLUA** campo `markdown`, `goNoGo` ou `diagnostic_tags`.',
    '',
  ].join('\n');
}

export function buildStructuredContractSuffix(mode: JoMode): string | null {
  if (mode === 'mapear')     return mapearContract(ALL_HOOK_IDS);
  if (mode === 'estruturar') return estruturarContract();
  if (mode === 'avaliar')    return avaliarContract();
  if (mode === 'construir')  return construirContract();
  if (mode === 'manter')     return manterContract();
  return null;
}
